version: '3.7'

services:
  db:
    container_name: db
    build:
      context: db/
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: SecretPasswordForDbWhichMayOrMayNotBeGuessable
      MYSQL_ROOT_PASSWORD: SecretRootPasswordForDbWhichMayOrMayNotBeGuessable
      MYSQL_DATBASE: highlightSharing
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  app:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
